// == ===
//a = 2 // atribuição
//console.log (1 == 1) //atribuição comparada
//console.log (1 == "1") //comparando numero e string da errado
//console.log (1 === "1")//coerção explicita ele compara por tipo depois por valor 
//console.log ( true == 1)//numero 1 é igual a true 
//console.log (1 == [1])
//console.log([] == false)
//console.log([] == [])

//const a = []
//const b = a
//console.log (a == b)

//const n1 = 2 
//const n2 = '3'

//const n3 = n1 + n2
//console.log(n3)
// const n4 = n1 + Number(n2)
//const n4 = n1 + +n2 //transforma o n em number
//console.log (n4)

//class Pessoa {
    //  void andar (){

        // }
        //a = 2;
        //a = andar ;
        //void m () {
            // a();
            //    }
            //}
//var idade = 18
//console.log ("oi," + nome)
//if (idade >= 18) {
    //çamento hoist o efeito do var iça o var nome para fora do if
    //  var nome "joão"
    // console.log ("Parabens,"+ nome + ". voce pode dirigir.")
    //printf ("parabens, %s", nome);
    // console.log (`parabens, ${nome}. voce pode didrigir .`)
    //}
    //console.log ("até mais, " + nome)

// nao pode declarar 2 variaveis com o mesmo nome 
//var linguagem = "javascript"
//console.log ("aprendendo," + linguagem)
//linguagem = "java"
//console.log ("aprendendo," + linguagem)

//const nome  = "jose"
//const idade = 27 
//nome =  "maria"
//const a 

//let a = 2
//let b = 'abc'
//let endereco = `rua K, 12 `
 
//var c = 2+3 
//var d = "abc"